name: 'my_new_project'
version: '1.0.0'
config-version: 2

# Use the same profile name as set in dbt Cloud
profile: 'default'  # dbt Cloud automatically manages this

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    example:
      +materialized: table
