name: 'dbt_snow_project'  
version: '1.0.0'
config-version: 2

# Use the same profile name as set in dbt Cloud
profile: 'default'  

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_snow_project:
    example:
      +materialized: table
    arc_model:  
      dw_mart:  
        +enabled: true
      staging_area:
        +enabled: true
